services:
  # https://github.com/grafana/grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  # https://github.com/prometheus/prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - 9090:9090

  nginx:
    image: nginx
    ports:
      - 8080:80

  # https://github.com/prometheus/node_exporter
  node-exporter:
    image: quay.io/prometheus/node-exporter
    ports:
      - 9100:9100
    depends_on:
      - prometheus

  # https://github.com/prometheus/alertmanager
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093

  # https://github.com/siimon/prom-client
  app:
    build: /app
    ports:
      - 4000:4000
    depends_on:
      - prometheus
