scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "nodejs"
    scrape_interval: 5s
    static_configs:
      - targets: ["app:4000"]

  - job_name: "nginx"
    scrape_interval: 5s
    static_configs:
      - targets: ["nginx-exporter:9113"]
